
sudo: required
services:
  - docker
script:
  - docker build -t rabrahams/multi-client ./client
  - docker build -t rabrahams/multi-nginx ./nginx
  - docker build -t rabrahams/multi-server ./server
  - docker build -t rabrahams/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rabrahams/multi-client:latest
  - docker push rabrahams/multi-nginx:latest
  - docker push rabrahams/multi-server:latest
  - docker push rabrahams/multi-worker:latest
