
sudo: required
services:
  - docker
script:
  - docker build -t richabrahams/multi-client ./client
  - docker build -t richabrahams/multi-nginx ./nginx
  - docker build -t richabrahams/multi-server ./server
  - docker build -t richabrahams/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push richabrahams/multi-client
  - docker push richabrahams/multi-nginx
  - docker push richabrahams/multi-server
  - docker push richabrahams/multi-worker
