sudo: required
services:
  - docker
node_js:
  - "11.10.1"
before_install:
  - docker build -t rabrahams/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rabrahams/react-test npm test -- --coverage

after_success:
  - docker build -t rabrahams/multi-client ./client
  - docker build -t rabrahams/multi-nginx ./nginx
  - docker build -t rabrahams/multi-server ./server
  - docker build -t rabrahams/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rabrahams/multi-client
  - docker push rabrahams/multi-nginx
  - docker push rabrahams/multi-server
  - docker push rabrahams/multi-worker